-- ============================================
-- Fase 3 (parte 2) — jogadores, partidas e gols
-- ============================================

-- Jogadores: 4 por clube em 8 times. time_id buscado pela sigla.
INSERT INTO jogadores (nome, posicao, numero_camisa, time_id) VALUES
('Pedro',           'Atacante', 9,  (SELECT id FROM times WHERE sigla='FLA')),
('Bruno Henrique',  'Atacante', 27, (SELECT id FROM times WHERE sigla='FLA')),
('Gerson',          'Meia',     8,  (SELECT id FROM times WHERE sigla='FLA')),
('Léo Pereira',     'Zagueiro', 4,  (SELECT id FROM times WHERE sigla='FLA')),
('Raphael Veiga',   'Meia',     23, (SELECT id FROM times WHERE sigla='PAL')),
('Dudu',            'Atacante', 7,  (SELECT id FROM times WHERE sigla='PAL')),
('Gustavo Gómez',   'Zagueiro', 15, (SELECT id FROM times WHERE sigla='PAL')),
('Weverton',        'Goleiro',  21, (SELECT id FROM times WHERE sigla='PAL')),
('Yuri Alberto',    'Atacante', 9,  (SELECT id FROM times WHERE sigla='COR')),
('Rodrigo Garro',   'Meia',     10, (SELECT id FROM times WHERE sigla='COR')),
('Fagner',          'Lateral',  23, (SELECT id FROM times WHERE sigla='COR')),
('Félix Torres',    'Zagueiro', 4,  (SELECT id FROM times WHERE sigla='COR')),
('Calleri',         'Atacante', 9,  (SELECT id FROM times WHERE sigla='SAO')),
('Lucas Moura',     'Meia',     7,  (SELECT id FROM times WHERE sigla='SAO')),
('Luciano',         'Atacante', 10, (SELECT id FROM times WHERE sigla='SAO')),
('Rafael',          'Goleiro',  23, (SELECT id FROM times WHERE sigla='SAO')),
('Hulk',            'Atacante', 7,  (SELECT id FROM times WHERE sigla='CAM')),
('Gustavo Scarpa',  'Meia',     14, (SELECT id FROM times WHERE sigla='CAM')),
('Everson',         'Goleiro',  22, (SELECT id FROM times WHERE sigla='CAM')),
('Júnior Alonso',   'Zagueiro', 5,  (SELECT id FROM times WHERE sigla='CAM')),
('Alan Patrick',    'Meia',     10, (SELECT id FROM times WHERE sigla='INT')),
('Rafael Borré',    'Atacante', 9,  (SELECT id FROM times WHERE sigla='INT')),
('Rochet',          'Goleiro',  1,  (SELECT id FROM times WHERE sigla='INT')),
('Vitão',           'Zagueiro', 4,  (SELECT id FROM times WHERE sigla='INT')),
('Cristaldo',       'Meia',     10, (SELECT id FROM times WHERE sigla='GRE')),
('Soteldo',         'Atacante', 7,  (SELECT id FROM times WHERE sigla='GRE')),
('Kannemann',       'Zagueiro', 4,  (SELECT id FROM times WHERE sigla='GRE')),
('Marchesín',       'Goleiro',  1,  (SELECT id FROM times WHERE sigla='GRE')),
('Tiquinho Soares', 'Atacante', 9,  (SELECT id FROM times WHERE sigla='BOT')),
('Marlon Freitas',  'Meia',     5,  (SELECT id FROM times WHERE sigla='BOT')),
('John',            'Goleiro',  1,  (SELECT id FROM times WHERE sigla='BOT')),
('Bastos',          'Zagueiro', 4,  (SELECT id FROM times WHERE sigla='BOT'));

-- Partidas: cada jogo no estádio do mandante (estadio_id derivado do time da casa)
INSERT INTO partidas (data_partida, time_casa_id, time_visitante_id, estadio_id, gols_casa, gols_visitante) VALUES
('2025-04-12', (SELECT id FROM times WHERE sigla='FLA'), (SELECT id FROM times WHERE sigla='BOT'), (SELECT estadio_id FROM times WHERE sigla='FLA'), 2, 1),
('2025-04-13', (SELECT id FROM times WHERE sigla='PAL'), (SELECT id FROM times WHERE sigla='COR'), (SELECT estadio_id FROM times WHERE sigla='PAL'), 1, 1),
('2025-04-14', (SELECT id FROM times WHERE sigla='SAO'), (SELECT id FROM times WHERE sigla='GRE'), (SELECT estadio_id FROM times WHERE sigla='SAO'), 3, 0),
('2025-04-15', (SELECT id FROM times WHERE sigla='CAM'), (SELECT id FROM times WHERE sigla='INT'), (SELECT estadio_id FROM times WHERE sigla='CAM'), 2, 2),
('2025-04-19', (SELECT id FROM times WHERE sigla='COR'), (SELECT id FROM times WHERE sigla='FLA'), (SELECT estadio_id FROM times WHERE sigla='COR'), 0, 2),
('2025-04-20', (SELECT id FROM times WHERE sigla='INT'), (SELECT id FROM times WHERE sigla='PAL'), (SELECT estadio_id FROM times WHERE sigla='INT'), 1, 0),
('2025-04-21', (SELECT id FROM times WHERE sigla='GRE'), (SELECT id FROM times WHERE sigla='CAM'), (SELECT estadio_id FROM times WHERE sigla='GRE'), 1, 3),
('2025-04-22', (SELECT id FROM times WHERE sigla='BOT'), (SELECT id FROM times WHERE sigla='SAO'), (SELECT estadio_id FROM times WHERE sigla='BOT'), 2, 1),
('2025-04-26', (SELECT id FROM times WHERE sigla='FLA'), (SELECT id FROM times WHERE sigla='PAL'), (SELECT estadio_id FROM times WHERE sigla='FLA'), 1, 1),
('2025-04-27', (SELECT id FROM times WHERE sigla='SAO'), (SELECT id FROM times WHERE sigla='CAM'), (SELECT estadio_id FROM times WHERE sigla='SAO'), 2, 2),
('2025-04-28', (SELECT id FROM times WHERE sigla='INT'), (SELECT id FROM times WHERE sigla='BOT'), (SELECT estadio_id FROM times WHERE sigla='INT'), 3, 1),
('2025-05-03', (SELECT id FROM times WHERE sigla='COR'), (SELECT id FROM times WHERE sigla='GRE'), (SELECT estadio_id FROM times WHERE sigla='COR'), 2, 0);

-- Gols: partida_id buscado pela data, jogador_id pelo nome
INSERT INTO gols (partida_id, jogador_id, minuto, tipo) VALUES
((SELECT id FROM partidas WHERE data_partida='2025-04-12'), (SELECT id FROM jogadores WHERE nome='Pedro'),           12, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-12'), (SELECT id FROM jogadores WHERE nome='Bruno Henrique'),  58, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-12'), (SELECT id FROM jogadores WHERE nome='Tiquinho Soares'), 74, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-13'), (SELECT id FROM jogadores WHERE nome='Dudu'),            33, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-13'), (SELECT id FROM jogadores WHERE nome='Yuri Alberto'),    80, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-14'), (SELECT id FROM jogadores WHERE nome='Calleri'),         15, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-14'), (SELECT id FROM jogadores WHERE nome='Luciano'),         40, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-14'), (SELECT id FROM jogadores WHERE nome='Lucas Moura'),     66, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-15'), (SELECT id FROM jogadores WHERE nome='Hulk'),            22, 'penalti'),
((SELECT id FROM partidas WHERE data_partida='2025-04-15'), (SELECT id FROM jogadores WHERE nome='Gustavo Scarpa'),  70, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-15'), (SELECT id FROM jogadores WHERE nome='Rafael Borré'),    50, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-15'), (SELECT id FROM jogadores WHERE nome='Alan Patrick'),    88, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-19'), (SELECT id FROM jogadores WHERE nome='Pedro'),           30, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-19'), (SELECT id FROM jogadores WHERE nome='Gerson'),          75, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-20'), (SELECT id FROM jogadores WHERE nome='Rafael Borré'),    61, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-21'), (SELECT id FROM jogadores WHERE nome='Soteldo'),         44, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-21'), (SELECT id FROM jogadores WHERE nome='Hulk'),            10, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-21'), (SELECT id FROM jogadores WHERE nome='Hulk'),            55, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-21'), (SELECT id FROM jogadores WHERE nome='Gustavo Scarpa'),  90, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-22'), (SELECT id FROM jogadores WHERE nome='Tiquinho Soares'), 25, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-22'), (SELECT id FROM jogadores WHERE nome='Marlon Freitas'),  70, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-22'), (SELECT id FROM jogadores WHERE nome='Calleri'),         80, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-26'), (SELECT id FROM jogadores WHERE nome='Bruno Henrique'),   5, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-26'), (SELECT id FROM jogadores WHERE nome='Raphael Veiga'),   52, 'penalti'),
((SELECT id FROM partidas WHERE data_partida='2025-04-27'), (SELECT id FROM jogadores WHERE nome='Calleri'),         18, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-27'), (SELECT id FROM jogadores WHERE nome='Luciano'),         63, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-27'), (SELECT id FROM jogadores WHERE nome='Hulk'),            40, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-27'), (SELECT id FROM jogadores WHERE nome='Hulk'),            85, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-28'), (SELECT id FROM jogadores WHERE nome='Rafael Borré'),    20, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-28'), (SELECT id FROM jogadores WHERE nome='Alan Patrick'),    48, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-28'), (SELECT id FROM jogadores WHERE nome='Rafael Borré'),    77, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-04-28'), (SELECT id FROM jogadores WHERE nome='Tiquinho Soares'), 90, 'penalti'),
((SELECT id FROM partidas WHERE data_partida='2025-05-03'), (SELECT id FROM jogadores WHERE nome='Yuri Alberto'),    35, 'normal'),
((SELECT id FROM partidas WHERE data_partida='2025-05-03'), (SELECT id FROM jogadores WHERE nome='Rodrigo Garro'),   70, 'normal');